#!/usr/bin/env bash

DOCKER_HUB_USERNAME=phryg1an

IMAGE_REPO=${DOCKER_HUB_USERNAME}
IMAGE_NAME=$1
IMAGE_VERSION=$2

SCRIPTS_DIR=$(cd "$(dirname "$0")"; pwd)
BASE_DIR=$(dirname "${SCRIPTS_DIR}")
IMAGES_DIR=${BASE_DIR}/images/phryg1an

if [ -z "${IMAGE_NAME}" ]; then
  echo "Usage: $0 <image-name> [<image-version>]"
  echo "Available images:"
  (
    cd "${IMAGES_DIR}"
    for image_name in *; do
      echo " * ${image_name}"
    done
  )
  echo "Default version: latest"
  exit 1
fi

[ -z "${IMAGE_VERSION}" ] && IMAGE_VERSION=latest

docker push "${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_VERSION}"
